# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='name client')),
                ('total', models.FloatField(verbose_name='total productos')),
                ('type_pay', models.CharField(choices=[('ef', 'efective'), ('po', 'point')], default='ef', max_length=2, verbose_name='tipo de pago')),
            ],
            options={
                'db_table': 'app_shopping_cart_client',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping_cart.Client')),
            ],
            options={
                'db_table': 'app_shopping_cart_sale',
            },
        ),
    ]
