# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0004_auto_20170402_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.FloatField(verbose_name='total productos'),
        ),
    ]
