# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0006_auto_20171022_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id sale'),
        ),
    ]
