# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0009_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='rif',
            new_name='it',
        ),
    ]
