# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0010_auto_20171023_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='password',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
