# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0011_auto_20171023_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='email',
            new_name='gmail',
        ),
        migrations.RenameField(
            model_name='business',
            old_name='password',
            new_name='gmail_password',
        ),
    ]
