# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-24 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0014_remove_business_gmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type_pay',
        ),
        migrations.AddField(
            model_name='sale',
            name='type_pay',
            field=models.CharField(choices=[('ef', 'efective'), ('po', 'point')], default='ef', max_length=2, verbose_name='tipo de pago'),
        ),
    ]
