# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name table'),
        ),
    ]
