# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20170214_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='minimum',
            field=models.IntegerField(default=0, verbose_name='minimum'),
        ),
        migrations.AddField(
            model_name='section',
            name='minimum_mode',
            field=models.BooleanField(default=False, verbose_name='minimum mode'),
        ),
    ]
