# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
