# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Increase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100, unique=True, verbose_name='name section')),
                ('increase', models.IntegerField(verbose_name='quantity increase')),
                ('increase_date', models.DateTimeField(verbose_name='date increase')),
            ],
            options={
                'db_table': 'app_article_increase',
            },
        ),
    ]
