# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170322_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='increase',
            name='increase',
            field=models.CharField(max_length=4, verbose_name='increase percentage'),
        ),
        migrations.AlterField(
            model_name='increase',
            name='section',
            field=models.CharField(max_length=100, verbose_name='name section'),
        ),
    ]
