# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170322_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='increase',
            name='increase',
            field=models.IntegerField(default=0, verbose_name='percentage increase'),
        ),
    ]
